name: blurhash_ffi
description: >-
  A compact, fast and easy to use blurry image placeholder generator for Flutter
  using native ffi bindings. 
version: 1.0.2 
repository: https://github.com/folksable/blurhash_ffi

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  logging: ^1.2.0

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

screenshots:
  - description: "Image 1 Selected"
    path: screenshots/1.png
  - description: "Image 2 Selected"
    path: screenshots/2.png
  - description: "Image 3 Selected"
    path: screenshots/3.png
  - description: "Image Unselected"
    path: screenshots/0.png

topics:
  - blurhash
  - ffi
  - images